### ISSUE TITLE
UnboundLocalError: local variable 'image_url' referenced before assignment

### ISSUE THREAD

**Issue by 1581088791lym** [StartHua/Comfyui_ALY#1]
使用插件的时候遇到这样的报错

got prompt
==========错误 start===========
HTTPSConnectionPool(host='openplatform.aliyuncs.com', port=443): Max retries exceeded with url: /?Product=imageseg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
==========错误 end===========
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/Comfyui_ALY/ALY_Seg_Cloth.py", line 90, in sample
    source_img = img_from_url(image_url)
UnboundLocalError: local variable 'image_url' referenced before assignment

看了阿里云后台，没有产生扣费，应该是调用失败的
![微信截图_20240122204137](https://github.com/StartHua/Comfyui_ALY/assets/148748322/848968f5-72ad-4092-9c03-d8c0a1c5ab21)
尝试添加了这串代码，禁用ssh，然后还是出现相同的报错额(￣_,￣ )

**Comment by jinnaluo0** [comment]
卸载掉python中所有的模块alibabacloud
重新执行这两个命令：
pip install alibabacloud_imageseg20191230 
pip install alibabacloud_tea_console
试下
